### ISSUE TITLE
InventoryOpenEvent

### ISSUE THREAD

**Issue by kingpyro** [gravitylow/AntiCheat#190] opened 2013-03-17 22:38 UTC
Hi getting this error in console. im not sure where its coming from or how to reproduce it.

2013-03-17 14:57:23 [SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v1.5.6
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.v1_5_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:501)
    at net.minecraft.server.v1_5_R1.EntityPlayer.openContainer(EntityPlayer.java:507)
    at net.minecraft.server.v1_5_R1.EntityMinecartContainer.a_(EntityMinecartContainer.java:229)
    at net.minecraft.server.v1_5_R1.EntityHuman.p(EntityHuman.java:777)
    at net.minecraft.server.v1_5_R1.PlayerConnection.a(PlayerConnection.java:1090)
    at net.minecraft.server.v1_5_R1.Packet7UseEntity.handle(SourceFile:36)
    at net.minecraft.server.v1_5_R1.Packet7UseEntity$$EnhancerByCGLIB$$55d41ff2.CGLIB$handle$0(<generated>)
    at net.minecraft.server.v1_5_R1.Packet7UseEntity$$EnhancerByCGLIB$$55d41ff2$$FastClassByCGLIB$$16b405a2.invoke(<generated>)
    at com.comphenix.net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at com.comphenix.protocol.injector.packet.ReadPacketModifier.intercept(ReadPacketModifier.java:98)
    at net.minecraft.server.v1_5_R1.Packet7UseEntity$$EnhancerByCGLIB$$55d41ff2.handle(<generated>)
    at net.minecraft.server.v1_5_R1.NetworkManager.b(NetworkManager.java:292)
    at net.minecraft.server.v1_5_R1.PlayerConnection.d(PlayerConnection.java:113)
    at net.minecraft.server.v1_5_R1.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.v1_5_R1.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_5_R1.MinecraftServer.r(MinecraftServer.java:580)
    at net.minecraft.server.v1_5_R1.DedicatedServer.r(DedicatedServer.java:225)
    at net.minecraft.server.v1_5_R1.MinecraftServer.q(MinecraftServer.java:476)
    at net.minecraft.server.v1_5_R1.MinecraftServer.run(MinecraftServer.java:409)
    at net.minecraft.server.v1_5_R1.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
    at org.bukkit.craftbukkit.v1_5_R1.inventory.CraftInventory.getContents(CraftInventory.java:57)
    at net.h31ix.anticheat.event.InventoryListener.onInventoryOpen(InventoryListener.java:66)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 23 more

Currently Running AntiCheat V1.5.6
Running CB B2665
Debug Log http://pastebin.com/tuneS0Fc

**Comment by gravitylow** [comment] 2013-03-17 22:49
https://github.com/h31ix/AntiCheat#bug-reportingsupportquestions

**Comment by kingpyro** [comment] 2013-03-19 00:40
Updated With Debug Link

**Comment by gravitylow** [comment] 2013-03-27 23:14
This is strange. The error seems to be coming from a line in the code `event.getInventory().getContents()` which is a Bukkit method. I don't do any looping or even calling of inventory indexes, so it seems improbable that an ArrayIndexOutOfBoundsException would come from there. The only possible place it could have come from is deeper in the code that parses the inventory, but the stack-trace never points to that.

With all that considered, I would say this is a Bukkit bug, but I'm going to have to do some digging and find out what caused this and if it is indeed a Bukkit bug. I'm a bit skeptical because this would be rather important and a hard thing to miss. 

So that I can work on this, what version of CB were you running?

**Comment by blablubbabc** [comment] 2013-04-08 16:48
I got the same I think, when it opens a chest when I use the /openinv feature of AdminCmd:

[SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v1.5.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:26)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
        at org.bukkit.craftbukkit.v1_5_R2.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:506)
        at net.minecraft.server.v1_5_R2.EntityPlayer.openContainer(EntityPlayer.java:510)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at be.Balor.Tools.Compatibility.Reflect.MethodUtils.invokeMethod(MethodUtils.java:154)
        at be.Balor.Tools.Compatibility.Reflect.MethodHandler.invoke(MethodHandler.java:55)
        at be.Balor.OpenInv.InventoryManager.openInv(InventoryManager.java:185)
        at be.Balor.OpenInv.InventoryManager.openInv(InventoryManager.java:175)
        at be.Balor.Manager.Commands.Player.OpenInventory.execute(OpenInventory.java:70)
        at be.Balor.Manager.Commands.ACCommandContainer.execute(ACCommandContainer.java:75)
        at be.Balor.Manager.CommandManager$NormalCommand.processCmd(CommandManager.java:90)
        at be.Balor.Manager.CommandManager$NormalCommand.run(CommandManager.java:104)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.minecraft.server.v1_5_R2.ItemStack;
        at sun.proxy.$Proxy33.getContents(Unknown Source)
        at org.bukkit.craftbukkit.v1_5_R2.inventory.CraftInventory.getContents(CraftInventory.java:55)
        at net.h31ix.anticheat.event.InventoryListener.onInventoryOpen(InventoryListener.java:58)
        at sun.reflect.GeneratedMethodAccessor273.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 21 more

**Comment by blablubbabc** [comment] 2013-04-08 16:49
Ah no, upps not the same.. but maybe related then.. :D

**Comment by gravitylow** [comment] 2013-04-11 23:52
That's an issue with OpenInv. That plugin has had multiple reported issues.

**Comment by blablubbabc** [comment] 2013-04-12 01:11
It works fine without AntiCheat.. :/ Anyway, I also posted a ticket on AdminCmd's ticket page. Note, this is NOT the OpenInv plugin, but a similiar feature of the AdminCmd plugin. I do not know if they are related besides the feature and the features name.

**Comment by gravitylow** [comment] 2013-04-12 01:48
You may not have any other plugins installed which ask for the inventories contents. Remember that you're dealing with a plugin that uses reflection to override Minecraft methods. This means that even though an error may be a specific plugin's fault, it may cause issues for others who are trying to use those same methods in a legitimate manor. This is why CB requires version-specific updating for CraftBukkit plugins. The issue actually occurs in this method: https://github.com/Belphemur/AdminCmd/blob/master/src/main/java/be/Balor/OpenInv/PlayerInventoryProxy.java#L136

**Comment by blablubbabc** [comment] 2013-04-12 02:25
Oh, I didn't know there was reflection going on in this plugin .. I thought changing a containers content would also be able with the default bukkit api / that this plugin would use these .. :( 
Anyway, thank you for this information

**Comment by Belphemur** [comment] 2013-04-13 14:24
I admit I made a little mistake in the return of getContent, thinking an array of object can be casted to an array or something else --''

But that doesn't mean using reflection is a bad thing, I don't have any choice but using reflection, else I have to release a version of the plugin specific to every bukkit version ... that is just the most stupidest thing bukkit had ever done.

It has broke plugin that was using minecraft class that haven't changed in YEARS just for the sake of "security".
I won't and will never remove the reflection and the proxy I use to make the OpenInvenotry feature works.

But I'm completely agree that my plugin is in fault here, and I returned the wrong structure. I'm going to correct that now.

Meaning, this issue has nothing to do with AntiCheat, and you can close it :)

**Comment by gravitylow** [comment] 2013-04-13 15:46
No I never said using reflection was a bad thing, I was just responding to his note that it "works fine without AntiCheat". Using reflection just means that errors in another plugin could be caused by an overridden method, even though it looks like its that plugin's fault.

Thanks for your response.

**Closed as completed by gravitylow** 2013-04-13 15:46 UTC
