### ISSUE TITLE
Getting too many false positives on interacting

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#66] opened 2012-06-13 04:54 UTC
Received 70 of these in five minutes, some a second apart from each other.  Wasn't able to watch the player to see what they were doing, but it was a trusted player without a modded client, and with a good connection.

00:36:07 [INFO] [AntiCheat] xxxxx tried to interact with an object that they couldn't see

> ver
> 00:45:22 [INFO] This server is running CraftBukkit version git-Bukkit-1.2.5-R4.0-b2222jnks (MC: 1.2.5) (Implementing API version 1.2.5-R4.0)
> ver AntiCheat
> 00:45:28 [INFO] AntiCheat version 1.3.2-DEV-b194
> 00:45:28 [INFO] Prevention of hacks and other malicious tinkering on a Minecraft server.
> 00:45:28 [INFO] Author: H31IX

**Comment by ZathrasNotTheOne** [comment] 2012-06-13 05:14
A little more info.  He was right-click placing slabs (half-height blocks) of stone as fast as he could.  Not sure how placing is "interacting", but that is what I saw.  Another player is stuck getting this when he logs in and is kicked immediately.  I'm backing out of 194 and going back to 190 for stability on my live server.

**Comment by SuperSpyTX** [comment] 2012-06-13 11:54
Sadly, there isn't much I can do now can I. (I'm going to be gone until sunday, with high expectations father).

So i'll put back the function that checks whether it's an interactable block and work on it some more (possibly maybe just add a delay).  If it all goes well, I'll either have a delay or just that check.

The whole point of the visuals check is to check and see if what the player he/she is interacting with, this includes block place/break.  I think what may be happening here is, originally I had a delay to check whether the player just interacted with a block or not.  I think what may have been a problem with my delay is, that after it was "detected", the delay would kick in and allow the player to interact for half a second.

I'm going to go ahead and reimplement this delay and then get back to you.

**Comment by SuperSpyTX** [comment] 2012-06-13 12:07
Please try build http://ci.h31ix.net/job/AntiCheat/195/ and report back results.

I tried to perform my false positive for this check and it doesn't give a damn.

EDIT: If the guy was placing a bunch of chests, he would still get the same false positives due to it being a interactable block.  I think a change can be done though to rectify this.  Let me know if that time comes.

**Comment by SuperSpyTX** [comment] 2012-06-13 13:55
Alrighty @ZathrasNotTheOne I'm also seeing light on the other part of the issue.  I'm working on this now.

**Comment by SuperSpyTX** [comment] 2012-06-13 14:31
Apparently the first part of the second half of the issue is fixed, but interacting on a pressure plate seems to be causing issues.

I will be unable to fix this until next sunday because i'll be with a father with high expectations.

**Comment by gravitylow** [comment] 2012-06-13 18:44
Try 198 http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/

**Comment by gravitylow** [comment] 2012-06-14 16:40
See if the latest build fixes the issue: http://ci.h31ix.net/job/AntiCheat/lastSuccessfulBuild/ as well

**Comment by gravitylow** [comment] 2012-06-15 15:01
We've decided to limit the visual check to only chests in preparation for 1.3.2 - we are planning to continue work on it after this build, that way it's not holding us up from a new version.

**Comment by SuperSpyTX** [comment] 2012-06-15 22:08
I'm going to go ahead and close this, i'm just going to reorganize it into a new issue i'm about to make.

Let's just say this is "fixed" and we'll move the issue elsewhere.

**Closed as completed by SuperSpyTX** 2012-06-15 22:08 UTC
Labels: Bug, Fixed, Confirmed
