### ISSUE TITLE
Speedhack prevention is not working

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#225] opened 2013-05-04 12:50 UTC
If someone uses the programm "Cheat Engine" and applys a speedhack, AntiCheat does not recognize it. I tested it myself on a non OP account and set the speed of my game 5x faster than normal. I was able to run around for a long time and did not get kicked or slowed down.

**Comment by gravitylow** [comment] 2013-05-04 18:22
Oh you're talking about the timer hack. Yes, I'm aware of this. I already having working protection against this in the code, but it's disabled internally right now because it was setting off false-positives. I need to get around to testing and refining it before I can enable it by default.

If you'd like to use it, you need to compile yourself.

Closing as a duplicate of https://github.com/h31ix/AntiCheat/issues/134

**Closed as completed by gravitylow** 2013-05-04 18:22 UTC
