### ISSUE TITLE
fire projectiles too fast

### ISSUE THREAD

**Issue by cuddylier** [gravitylow/AntiCheat#107] opened 2012-07-01 22:08 UTC
I have been experiencing a bug where anticheat thinks everyone throwing items is hacking e.g. throwing snow balls, eggs or xp bottles. Here is the debug from one player that was experiencing it, http://pastebin.com/MDH7jcaZ . Even with the permission anticheat.check.exempt the players still get kicked for hacking.

**Comment by gravitylow** [comment] 2012-07-10 16:07
Duplicate of the one on our site, closing this because it's resolved.

**Closed as completed by gravitylow** 2012-07-10 16:07 UTC
