### ISSUE TITLE
False Kick/Fly Message if Players use our Stargates

### ISSUE THREAD

**Issue by Elharter** [gravitylow/AntiCheat#171] opened 2013-01-31 10:05 UTC
Bukkit 1.4.6
AntiCheat + Stargate.

Anticheat is installed since 30minutes and many clean player are kicked.

If a player use a Stargate portal, Serverlog says:
2013-01-31 11:05:00 [INFO] Elharter tried to fly on y-axis 28 times (max =1)
2013-01-31 11:05:01 [INFO] Elharter tried to fly on y-axis 32 times (max =1)
2013-01-31 11:05:01 [INFO] [Stargate::hasPerm::SuperPerm(Skadiee)] stargate.use
=> true
2013-01-31 11:05:01 [INFO] [Stargate::hasPerm::SuperPerm(Skadiee)] stargate.use
=> true
2013-01-31 11:05:01 [INFO] [Stargate::hasPerm::SuperPerm(Skadiee)] stargate.free
 => false
2013-01-31 11:05:01 [INFO] [Stargate::hasPerm::SuperPerm(Skadiee)] stargate.free
.use => false
2013-01-31 11:05:01 [INFO] Elharter tried to fly on y-axis 36 times (max =1)
2013-01-31 11:05:01 [INFO] Skadiee tried to fly on y-axis 172 times (max =1)
2013-01-31 11:05:01 [INFO] Skadiee tried to fly on y-axis 176 times (max =1)
## 2013-01-31 11:05:02 [INFO] ----------------------[AntiCheat]--------------------

2013-01-31 11:05:02 [INFO] Elharter has just entered the medium hack level.
2013-01-31 11:05:02 [INFO] Elharter's last failed check was: Fly.
2013-01-31 11:05:02 [INFO] Type '/anticheat report Elharter' for more informatio
n.
2013-01-31 11:05:02 [INFO] -----------------------------------------------------
## 2013-01-31 11:05:02 [INFO] ----------------------[AntiCheat]--------------------

2013-01-31 11:05:02 [INFO] Elharter has just entered the medium hack level.
2013-01-31 11:05:02 [INFO] Elharter's last failed check was: Fly.
2013-01-31 11:05:02 [INFO] Type '/anticheat report Elharter' for more informatio
n.
2013-01-31 11:05:02 [INFO] -----------------------------------------------------

2013-01-31 11:05:02 [INFO] Elharter tried to fly on y-axis 40 times (max =1)
2013-01-31 11:05:02 [INFO] Skadiee tried to fly on y-axis 180 times (max =1)
2013-01-31 11:05:02 [INFO] Skadiee tried to fly on y-axis 184 times (max =1)
2013-01-31 11:05:02 [INFO] Skadiee tried to fly on y-axis 188 times (max =1)
2013-01-31 11:05:02 [INFO] Skadiee tried to fly on y-axis 192 times (max =1)
2013-01-31 11:05:03 [INFO] Skadiee tried to fly on y-axis 196 times (max =1)

And the Player will be kicked. 
Thats crap.

All clean Player will be kicked now.

please help

**Comment by Elharter** [comment] 2013-01-31 13:19
Our report: http://pastebin.com/Fjyr2DL4

**Comment by gravitylow** [comment] 2013-01-31 22:15
Duplicate of https://github.com/h31ix/AntiCheat/issues/146 closing.

**Closed as completed by gravitylow** 2013-01-31 22:15 UTC
