### ISSUE TITLE
Speed II potions not working (possibly Speed I also)

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#18] opened 2012-05-31 14:19 UTC
When you drink Speed potions you cannot run properly. Please fix!

**Comment by SuperSpyTX** [comment] 2012-05-31 16:36
This could be a actual bug.  I'll mark this as confirmed until I'm proven wrong.

**Comment by Murabitos** [comment] 2012-05-31 16:40
Could be? :P I have a server full of people complaining haha..

Gioboi.g.nfoservers.com - pvp/anarchy/grief

**Comment by Rojoss** [comment] 2012-05-31 18:25
I third this.
Speed potions aren't working good.

**Comment by SuperSpyTX** [comment] 2012-05-31 22:38
When you guys get the chance, test this devbuild http://ci.h31ix.net/job/AntiCheat/134/

Then report results back to me and see if this resolved issue or not.

**Comment by SuperSpyTX** [comment] 2012-06-01 13:37
I am going to assume this was fixed.

**Comment by Rojoss** [comment] 2012-06-01 14:43
Will test it once jenkins is back up.

**Comment by SuperSpyTX** [comment] 2012-06-01 17:25
Because of Cloudflare, I've downloaded the devbuild directly from the CI.

Here you go http://www.mediafire.com/download.php?qwke8m4n554cubm

**Comment by SuperSpyTX** [comment] 2012-06-02 03:10
Assumes this is now fixed.

**Closed as completed by SuperSpyTX** 2012-06-02 03:10 UTC
Labels: Bug, Fixed, Confirmed
