### ISSUE TITLE
TnT explosions buggy and tp you to the ground

### ISSUE THREAD

**Issue by Rojoss** [gravitylow/AntiCheat#37] opened 2012-06-06 16:26 UTC
When you are next to tnt it should launch you in air.
But instead you go in air and get tped down for flying/moving.

**Comment by SuperSpyTX** [comment] 2012-06-06 19:00
Finally, I can confirm this because mass slapping everybody with CommandBook can also throw a false positive.

I will fix this one later.

**Comment by SuperSpyTX** [comment] 2012-06-09 01:45
http://ci.h31ix.net/job/AntiCheat/164/  - Test if this fixes your problem.

My issue with CommandBook is now resolved.

**Comment by SuperSpyTX** [comment] 2012-06-09 01:55
Ok i just did this like what, 3 times.  I've updated both my comments with the build you SHOULD be using now.

**Comment by SuperSpyTX** [comment] 2012-06-09 17:51
I'll go ahead and close this issue, if you still have problems, feel free to reply.

**Closed as completed by SuperSpyTX** 2012-06-09 17:51 UTC
Labels: Bug, Fixed, Confirmed
