### ISSUE TITLE
AntiCheat entity check causing spam.

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#105] opened 2012-06-30 16:20 UTC
Using anticheat  #248, it seems that there is a bug where it continues to report lagging or hacked clients and doesn't stop, even if the player is offline. I had to download the latest version on dev bukkit so I don't see the spam. :(

**Comment by ghost** [comment] 2012-06-30 17:44
Also seems to be an issue with entities when being thrown. For example, throwing snowballs spams the staff with error reports and not all snowballs are thrown.

**Comment by cuddylier** [comment] 2012-07-01 22:06
i am experiencing this on latest dev as well.

**Comment by gravitylow** [comment] 2012-07-10 16:07
Duplicate of cuddylier's issue and the one on our site, closing because it's resolved.

**Closed as completed by gravitylow** 2012-07-10 16:07 UTC

**Comment by ghost** [comment] 2012-07-10 19:19
;-; Yet I posted it first. Alright then.
