### ISSUE TITLE
Have Anti Cheat load when i dont even have the plugin.

### ISSUE THREAD

**Issue by jenks1999** [gravitylow/AntiCheat#274] opened 2014-02-12 02:31 UTC
I seem to currently get AntiCheat auto download everytime i load my server even though i dont have AntiCheat.jar on my computer at all. What makes matters worse is, it crashes my server when someone opens a chest and also spamms my console with over 400,000kbs of data in 30 seconds. i have tried blocking the plugin but it just seems to make matters worse. I have added 1 at a time the plugins and none seem to start it then suddenly it kicks in again. I want your interfeering plugin gone. I didnt want it present due to this very reason and yet the plugin seems to force its way onto my server. Correct this immediately please.

**Comment by jenks1999** [comment] 2014-02-12 02:32
2014-02-11 16:18:30 [SEVERE] Could not pass event InventoryOpenEvent to AntiCheat v2.0.1 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437) at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31) at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479) at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464) at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:617) at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:382) at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:352) at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2719) at thermalexpansion.block.dynamo.TileDynamoBase.openGui(TileDynamoBase.java:193) at thermalexpansion.block.BlockTEBase.func_71903_a(BlockTEBase.java:61) at thermalexpansion.block.dynamo.BlockDynamo.func_71903_a(BlockDynamo.java:90) at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:524) at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:896) at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonPlayerConnection.func_72472_a(CommonPacketHandler.java:349) at net.minecraft.network.packet.Packet15Place.func_73279_a(Packet15Place.java:79) at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470) at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233) at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54) at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:914) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:781) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663) at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16) Caused by: java.lang.AbstractMethodError at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftInventory.getContents(CraftInventory.java:42) at net.gravitydevelopment.anticheat.event.InventoryListener.onInventoryOpen(InventoryListener.java:59) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435) ... 24 more

**Comment by DarkArc** [comment] 2014-02-12 02:55
AntiCheat does not force itself into any server. This is either being done by another plugin, or if you use one, a control panel, and possibly a hosting provider.

**Comment by gravitylow** [comment] 2014-02-12 11:51
The above is correct. I have no possible way of installing AntiCheat on a server. The only way this can happen is if a user installs it or if you have another plugin downloading it.

In fact, I would be willing to bet that one of your plugins has a broken Updater class. I am the developer of a [system](http://forums.bukkit.org/threads/updater-2-1-easy-safe-and-policy-compliant-auto-updating-for-your-plugins-new.96681/) that allows plugins to easily auto-update. Since AntiCheat is my plugin, I give an example that contains the BukkitDev ID of the AntiCheat project. I believe that someone may have copy-pasted this example verbatim into their own plugin without changing the ID to THEIR project. Thus, every time the server starts, AntiCheat is downloaded as an "update" to their plugin because they misconfigured it.

The way to verify this: remove AntiCheat from the plugins folder, start your server, wait a bit (30 seconds or so) and then check the contents of the "update" folder inside your plugins folder. If this folder contains an AntiCheat.jar, my theory is correct.

The way to fix this: I can't do anything from my end to correct this problem. The author of the plugin needs to fix their broken code. However, I would be willing to help you identify which plugin you have that is causing this problem. If you would provide me with a list of your plugins, I will personally go through them and find out which one is using the wrong ID and downloading my plugin onto your server.

Furthermore, I have edited the post that I linked to earlier to remove any instances of my ID from the page and its examples. This should prevent any negligent developer from making this mistake again.

**Comment by jenks1999** [comment] 2014-02-12 13:57
Here are 3 screenshots with a list of all the folders and jar files to match. I have checked again 1 by one and sometimes it takes 2 hours for the plugin to suddenly appear. This is baffling me because I thought it was the updater folder but it is disabled.

Here are screenshots of my files so you can see exactly what I have and their file sizes.
http://puu.sh/6Tg5b.png
http://puu.sh/6Tg5Q.png
http://puu.sh/6Tg6i.png

**Comment by gravitylow** [comment] 2014-02-12 19:04
Did you check inside the "update" folder to see if the plugin was being downloaded there?

I've been looking through most of these and haven't been able to find any misconfigured Updaters yet.

**Comment by jenks1999** [comment] 2014-02-12 23:17
My 2 updater files are disabled and do not download anything here are the screenies for your information.

http://puu.sh/6TPbQ.jpg
http://puu.sh/6TPdg.png

**Comment by gravitylow** [comment] 2014-02-13 22:52
You must set disable to "true" if you actually want to disable it.

**Comment by jenks1999** [comment] 2014-02-13 22:57
Done and still no difference.

**Comment by jenks1999** [comment] 2014-02-14 02:21
Any info on the error also that happens each time someone opens a chest? I am using tekkit 1.2.0 also but i dont see how the mods on there would also effect this.

**Comment by gravitylow** [comment] 2014-02-15 05:57
Yeah the error isn't really relevant to the issue at hand. It's caused by the fact that you're not running Bukkit, but the issue you're presenting is that AC is on your server when you don't want it to be.

The bottom line, though, is that _I_ am not doing anything that could feasibly make this happen. If AntiCheat is installed by the server admin, it has an option to download new updates once they're released. However, if you remove the plugin my code never ever runs on the server. So therefore it's another plugin or a mod of your server that's doing the downloading of the plugin.

I did go through all the plugins you screenshotted (the latest versions I could find on BukkitDev) and didn't see any using my project ID, but that doesn't mean you don't have a version which is doing that. I also don't know anything about tekkit or its mods so I'm not going to be of an use there.

In any case, I'm going to be closing this issue because it's invalid. AntiCheat has no capability to download itself onto a server where it does not exist. If I can help you identify what is doing the downloading I would be more than happy to assist.

**Closed as completed by gravitylow** 2014-02-15 05:57 UTC

**Comment by jenks1999** [comment] 2014-02-16 04:02
as you seem to not believe my information I will record a live video of this occurring and show you with a Fraps file, as there is obviously an error somewhere and I am using MCPC which is a bukkit supported jar file which allows tekkit to accept bukkit plugins. As there are no programs on the Tekkit server downloading this file as a raw data extract, but the second I add all these plugins from bukkit your file appears, it has to be in some way one of these and I have to use 1.6.4 as bukkit hasn't released the new MCPC version yet. I repeat BUKKIT has not yet released the new MCPc version. Thank you for your time and efforts in looking. I will learn java and find the issue myself. Maybe advise others on a plugin blocker program with anticheat as default might work. Thank you.

**Comment by gravitylow** [comment] 2014-02-16 06:05
1) I did not say I don't believe you. I do believe that you have this issue. 

What I am attempting to tell you is that **I don't have any power to do this** and therefore it's not coming from any of my work. That is to say there is no code that I have written that could possibly install AC on a server in which it does not exist. 

That does not invalidate your issue, it just means that it's not technically **my** issue. However, as I have said above and demonstrated to you, I am willing to help you get to the bottom of it. For me to do that, though, you need to not be hostile and understand that this bug is not my fault. It physically cannot be.

2) MCPC is **NOT** a "bukkit supported jar file" **NOR** does Bukkit in any way, shape, or form support MCPC. Just because MCPC uses Bukkit code does **NOT** mean it is a Bukkit project. You are very, very mistaken in this fact.

 I support vanilla Bukkit with AntiCheat. My point in bringing up this discrepancy is that there are changes made to MCPC that are not in Bukkit and could potentially be causing this problem. The changes made by the MCPC team are solely made by them and do not have anything to do with Bukkit.
