### ISSUE TITLE
Ladder (tried to fly on y-axis)

### ISSUE THREAD

**Issue by ghost** [gravitylow/AntiCheat#41] opened 2012-06-08 17:50 UTC
Using build #156

Player says they cannot climb a ladder because it thinks they're hacking. In the log I see this:

[SEVERE] [AntiCheat] player tried to fly on y-axis

Not sure what else you need but if there's anything else I can do to help just let me know =)

**Comment by SuperSpyTX** [comment] 2012-06-08 18:46
Do you have this issue when using AntiCheat build #155?

I'm just making sure.

**Comment by ghost** [comment] 2012-06-08 19:11
Nope, I downgraded and it went away.

**Comment by gravitylow** [comment] 2012-06-08 19:44
Fixed here: http://ci.h31ix.net/job/AntiCheat/160/ , please reply and confirm that it is fixed.

**Comment by ghost** [comment] 2012-06-09 14:48
It seems to do this still with Minecarts

**Comment by gravitylow** [comment] 2012-06-09 14:52
Refer to this issue: https://github.com/h31ix/AntiCheat/issues/44 , also please tell me if /this/ issue is fixed so I can close it.

**Comment by ghost** [comment] 2012-06-09 15:08
Ladders doesn't seem to happen anymore from what I can see but its happening with other things I could make new issues about

**Comment by gravitylow** [comment] 2012-06-09 15:18
That'd be preferred, the title means everything when looking through issues. So I'll go ahead and close this since the issue is fixed, you can add a new one for other things (you don't have to create a new issue for every single item that causes this, just make it known in the title which ones you are going to talk about in the issue)

**Closed as completed by gravitylow** 2012-06-09 15:18 UTC
Labels: Bug, Fixed, Confirmed
