### ISSUE TITLE
Players losing inventory on attack in pvp

### ISSUE THREAD

**Issue by tara81** [gravitylow/AntiCheat#235] opened 2013-05-18 19:01 UTC
http://pastebin.com/6mnRUXMX

Players are losing their inventory randomly when attacking other players??!  They keep their armor but their inventory disapears?!

**Comment by gravitylow** [comment] 2013-05-26 06:23
Which players? Your log is verryyyy long.

**Comment by tara81** [comment] 2013-05-26 16:41
xana . TyaFi , joshop

**Comment by tara81** [comment] 2013-05-26 16:46
sorry I have a long log =( Its a rare bug it gets reported to me once every day + every second day.

**Comment by gravitylow** [comment] 2013-05-27 05:26
I see this: TyAfi666 clicked inventory slots 10 times in 2 ms (max=10 in 50 ms)
AntiCheat will usually try to reverse any actions executed on an inventory if the slots are clicked too quickly.
It shouldn't result in the loss of inventory, but as you can tell the clicking is extremely fast (2 ms compared with the allowed 50ms). This could be because of lag, but I'd need further testing to determine.

**Comment by DarkArc** [comment] 2013-05-27 18:50
I think this is probably the same bug as Issue #224

**Comment by tara81** [comment] 2013-05-27 22:43
Okay, when it happens again i will get another log.  Some players dont report it . I have a server of 100 pop usually

**Comment by gravitylow** [comment] 2013-06-01 16:54
Closing as a duplicate of https://github.com/h31ix/AntiCheat/issues/224 - please contribute there so we can keep this organized.

**Closed as completed by gravitylow** 2013-06-01 16:54 UTC
