### ISSUE TITLE
Player teleporting through ground by edge

### ISSUE THREAD

**Issue by Tehyoda** [gravitylow/AntiCheat#42] opened 2012-06-08 18:12 UTC
A player on my server experienced a weird bug where they would teleport through the ground when sneaking and they approach an edge.

I removed all plugins on my server except AntiCheat and the player still had the problem.
I then put all the plugins back and removed AntiCheat, and the problem was solved.

Here is a video of it, since It makes trying to explain a lot easier:
http://www.youtube.com/watch?v=BC70Uui0vP4

**Comment by SuperSpyTX** [comment] 2012-06-08 18:45
This is a duplicate of issue #30

**Closed as completed by SuperSpyTX** 2012-06-08 18:45 UTC
Labels: Duplicate
