### ISSUE TITLE
"User tried to fly" while going up a 1x1 tower of water.

### ISSUE THREAD

**Issue by Jeebiss** [gravitylow/AntiCheat#131] opened 2013-01-01 02:30 UTC
< Jeebiss> I think I found a bug
< Jeebiss> When a user was going up a really large tower of water
< Jeebiss> It flagged him with flying
@SuPaHsPii Jeebiss: What kind, y-axis or just "tried to fly"
< Jeebiss> "Tried to fly"
< Jeebiss> Also, one second
< Jeebiss> Ill get the pastebin
< Jeebiss> http://pastebin.com/DeZz9ctu
@SuPaHsPii Define water tower? Just swimming up inside the water, or the side of the water (1 half in water, 1 half out)
< Jeebiss> Like a 1x1 pilar of water thats flowing off a block really high up

**Comment by SuperSpyTX** [comment] 2013-01-01 02:41
Alright thanks, will work on this.

EDIT: Reason why I assigned to myself is because

@SuPaHsPii There's just some complicated logic in my flight check that I have to work on

**Comment by TnTBass** [comment] 2013-01-02 18:17
Confirmed.

**Comment by gravitylow** [comment] 2013-01-03 00:41
Unless you changed it, there was an additional speed limit (with more leniency) already implemented in flight for those in (or next to) a waterfall.

**Comment by SuperSpyTX** [comment] 2013-01-03 04:47
@h31ix I think I may have changed it.

**Comment by gravitylow** [comment] 2013-01-14 21:39
Can you check this on the latest dev? It seems to be working fine for me.

**Comment by gravitylow** [comment] 2013-01-19 00:38
Any update on this?

**Comment by gravitylow** [comment] 2013-01-24 02:48
Closing, let me know.

**Closed as completed by gravitylow** 2013-01-24 02:48 UTC
Labels: Bug, Confirmed
